[functions]
  node_bundler = "esbuild"

[functions."ai"]
  timeout = 26
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[build]
  publish = "."
